# Generated by Django 4.2 on 2024-01-27 12:15

from django.db import migrations, models
import django.db.models.deletion
import medulla__rs.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmbulanceServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('BASIC', 'Basic Life Support (BLS)'), ('ADVANCED', 'Advanced Life Support (ALS)'), ('MOBILITY', 'Patient Transfer Service (PTS)'), ('AIR', 'Air Ambulance Service (AAS)'), ('MORTUARY', 'Mortuary Ambulance Service (MAS)')], default='BASIC', max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='AmbulanceVehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('VAN', 'Ambulance Van'), ('SPRINTER', 'Ambulance Sprinter'), ('SUV', 'Ambulance SUV'), ('MOTORCYCLE', 'Ambulance Motorcycle'), ('OTHER', 'Other')], default='VAN', max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PublicQueryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email_address', models.EmailField(max_length=255)),
                ('phone_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AmbulanceDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=15)),
                ('ambulance_number', models.CharField(max_length=15, unique=True)),
                ('license_number', models.CharField(blank=True, max_length=255)),
                ('driving_experience', models.IntegerField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('driver_image', models.ImageField(blank=True, null=True, upload_to=medulla__rs.models.DriverImageStorage.get_path)),
                ('ambulance_service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medulla__rs.ambulanceservicetype')),
                ('ambulance_vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medulla__rs.ambulancevehicletype')),
            ],
        ),
    ]
