# Generated by Django 5.0.1 on 2024-01-26 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medulla__rs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmbulanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('VAN', 'Ambulance Van'), ('SPRINTER', 'Ambulance Sprinter'), ('SUV', 'Ambulance SUV'), ('MOTORCYCLE', 'Ambulance Motorcycle'), ('OTHER', 'Other')], default='VAN', max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='AmbulanceDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=15)),
                ('ambulance_number', models.CharField(max_length=15, unique=True)),
                ('license_number', models.CharField(blank=True, max_length=255)),
                ('driving_experience', models.IntegerField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('ambulance_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medulla__rs.ambulancetype')),
            ],
        ),
    ]
