# Generated by Django 5.0.1 on 2024-01-26 09:48

import medulla__rs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medulla__rs', '0002_ambulancetype_ambulancedriver'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulancedriver',
            name='driver_image',
            field=models.ImageField(blank=True, null=True, upload_to=medulla__rs.models.DriverImageStorage),
        ),
    ]
